

# preprocessing config
preprocessing:
  flow_cut: 1000
  fhigh_cut: 2
  order_low: 4
  order_high: 4
  flip_polarity: False

#flip_polarity: False

pulse_identification:
  threshold: 50
  detrend: "quadratic"

ipi_identification:
  window_min: 2.5
  mad_outlier_threshold: 6

ibi_identification:
  peak_prominence: 5
  peak_width: 0.5
  mindist_perc: 0.25
  min_peaks: 2
  npeaks: 8

output:
  store_flag: True
  savefig_flag: True